FORMAT: 1A
HOST: http://ltfhc-next.hact.net

# LTFHC
This API provides full access to the LTFHC forms system UI. 
All JSON must be valid [JSON Schema](http://json-schema.org/latest/json-schema-core.html) or [JSON Hyper-Schema](http://json-schema.org/latest/json-schema-hypermedia.html).
The forms system UI uses the [JSONForm](https://github.com/joshfire/jsonform) Javascript library to generate HTML5 forms for presentation to the user.

# Group Collections
Collections are simple key-value pair lists of items (diseases, villages, etc). 

## Collection Lists [/lists]
### List all Lists [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Drugs"
        }, {
          "id": 2, "title": "Villages"
        }]

### Create a List [POST]
+ Request (application/json)

        { "title": "Drugs", [ "Asprin", "Vitamin C", "Amoxicillin" ] }

+ Response 201 (application/json)

        { "id": 1, "title": "Drugs", [ "Asprin", "Vitamin C", "Amoxicillin" ] }

### Retrieve a List [/lists/{id}]
A list with its items

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the list to perform action with. Has example value.
